### ISSUE TITLE
As a user my submission will be executed on a server after uploading

### ISSUE THREAD

**Issue by ronalddenouden** [SEP-TU-e-2024/website#103]
## Description
From stored submissions, a new submission is taken and together with the correct simulator/validator run on a server. This does not yet include the run settings (amount of cpu etc). The resulting metrics can be stored.

### Acceptance Criteria
- [x] A stored submission (from an upload to the platform) can be combined with a simulator/validator (1 example is enough)
- [x] The submission code is run with the simulator/validator on the server
- [x] The result of the evaluation is stored

### Requirements
- [ ] URF 9.3

**Comment by TPGamesNL** [comment]
See https://github.com/SEP-TU-e-2024/JudgeQueuer/pull/18 and https://github.com/SEP-TU-e-2024/website/pull/150

**Comment by TPGamesNL** [comment]
last one for review is https://github.com/SEP-TU-e-2024/website/pull/166
