### ISSUE TITLE
As a system I can send emails to users (back-end)

### ISSUE THREAD

**Issue by Doodshoofdaapje** [SEP-TU-e-2024/website#20]
## Description
The system can send an email with content to an email address. This functionality will need to be used for email verification as a way for users to authenticate themselves on the platform.

## Acceptance Criteria
- [x] The system can send an email with text content to a valid email addresses

**Comment by Doodshoofdaapje** [comment]
Progress of this can be found in the main branch in either the auth_views.py or submit_views.py in the send email methods

**Comment by TPGamesNL** [comment]
![Image](https://github.com/SEP-TU-e-2024/website/assets/29547183/5fd018d5-c155-4873-b11c-d341217dbbcb)
