### ISSUE TITLE
As a user I can have an overview of a problem occurence (front-end)

### ISSUE THREAD

**Issue by ThijsEgberts** [SEP-TU-e-2024/website#3]
## Description
As a user I can navigate form the overview of problem occurences to a specific overview for a selected problem occurence. 

### Acceptance Criteria
- [x] There is a problem occurence overview page
- [ ] The problem occurence overview page can be navigated to from the overview of problem occurences
- [x] There is room for information on the problem occurence overview regarding settings, metrics and more.

### Requirements
- [ ] URF 4.2

**Comment by ronalddenouden** [comment]
The basics have been created, connection from problem occurence overview/list needs to still be made. First version has been merged to main. The UI will need changes later based upon the client feedback.
