### ISSUE TITLE
As a PO I want the SDD to have a system overview (SDD Section 2)

### ISSUE THREAD

**Issue by Booksh** [SEP-TU-e-2024/website#35]
## Description
An initial version of the System overview section (section 2) of the SDD is written. This includes a section on the relation to current projects, as well as a section on the relation to predecessor and successor projects, a section explaining the function and purpose of the system, a section detailing the environment the system is meant to be used in and a section talking about the relation of the system to other systems.

### Process
- [x] A draft version has been written (no term references)
- [x] Feedback has been given
- [ ] The section has been refined after feedback (references are added for terms)

### Acceptance criteria:
- [x] Section 2.1 contains an explanation of the context of this project in relation to other current projects
- [x] Section 2.2 contains an explanation of the context of this project in relation to past and future projects
- [x] Section 2.3 contains a general overview of the function and purpose of the product, including a domain model, defining and discussing concepts of the system
- [x] Section 2.4 contains an explanation of the hardware and operating system of target system and development system, as well as who will use the system (user roles in URD)
- [x] Section 2.5 explains whether the product is part of an independent system, part of a larger system, replacing another system as well as the essential characteristics of these other systems

**Comment by vlhtg** [comment]
Furthermore, someone filled in 2.4 and 2.5. It is nicely written and covers our purposes.

**Comment by vlhtg** [comment]
Yes, 2.1, 2.2, 2.3 are fine!
Just one Latex thing, please don't use // for a new line. It is not meant for paragraphs. Use an empty line (press Enter two times).

**Comment by Booksh** [comment]
> Yes, 2.1, 2.2, 2.3 are fine! Just one Latex thing, please don't use // for a new line. It is not meant for paragraphs. Use an empty line (press Enter two times).

I fixed these
