### ISSUE TITLE
As a system I store the specified problems (back-end)

### ISSUE THREAD

**Issue by ronalddenouden** [SEP-TU-e-2024/website#90]
## Description
The platform will support at least 2 optimization problems:
- Time Slotting problem
- Vehicle Routing problem

The system stores specified problems. The associated data can be stored for more problem. For now it will be stored for the two optimization problems above.

### Acceptance Criteria
- [x] The system stores specified problems
- [x] The system stores the problem category associated to a specified problem
- [x] The system stores the (scoring) metrics associated to the specified problems
- [x] The system stores the benchmark set/problem instances associated to the specified problems. 
- [x] Have an example specified problem stored.
- [x] Validator from pyVRP is present and can be used

### Requirements
- [ ] URF 4.1 (part of)
- [ ] URF 5.1 TSP
- [ ] URF 5.2 VRPTW

### Refinement
Requires implementing the datamodel that was defined before. Adding how to do the different settings/metrics and linking it to a validator.

**Comment by Doodshoofdaapje** [comment]
All information regarding specified problems are currently being stored. In addition, there is a backend endpoint to download the files from blob. Progress can be tracked in https://github.com/SEP-TU-e-2024/website/pull/140
