### ISSUE TITLE
As a system I will report back the collected result (metrics) of a submission evaluation

### ISSUE THREAD

**Issue by ronalddenouden** [SEP-TU-e-2024/website#94]
## Description
The main goal of running submissions is to collect metrics during the execution of the solution. The system should report the metrics and store it such that we can later report the metrics back to the user.

The collection of metrics itself is part of a different user story.

### Acceptance Criteria
- [x] The format the metrics are stored in can be used for leaderboard purpose

### Requirements
- [ ] URF 12.2

**Comment by vlhtg** [comment]
https://github.com/SEP-TU-e-2024/runner_container/pull/16 starts to solve this. A way to push them to the database is needed next.
